### PR TITLE
LDA with K topics

### PR DESCRIPTION
**Pull request by amrimuhaimin**

### CODE REVIEW

**Comment by lizzzi111** [comment]
Dear Muhaimin,

Please address the following:
the name of the quantlet in the metainfo.txt should be the same as of the python (.py or .ipynb) script.
(So either you need to have SDA_class2020_NCTU_Abstract_LDA_LDAAnalysis as the name of the quantlet of both files: the metainfo file and of the .py (or .ipynb) scripts, or both should have the name Abstract_LDA_K_topics). Could you please adjust one of the names to make it consistent? Thank you. If you have further questions - do not hesitate to contact me.
Otherwise, we won't be able to create the README.md file automatically.

Best regards,
Elizaveta

**Comment by haerdle** [comment]
this is JANEs job to control this


*+*=2*

Wolfgang Karl Härdle
Ladislaus von Bortkiewicz Professor of Statistics
School of Business and Economics
Humboldt-Universität zu Berlin
Unter den Linden 6
10099 Berlin, Germany

Website:  hu.berlin/wkh <https://www.wiwi.hu-berlin.de/de/forschung/irtg/lvb/members/personalpages/wh>
Cryptocurrency Index: thecrix.de <http://thecrix.de/>
Financial Risk Meter: https://www.firamis.de/frm/ <https://www.firamis.de/frm/>
Blockchain Research Center: hu.berlin/BRC <https://www.wiwi.hu-berlin.de/de/forschung/irtg/blockchain-research-center>
Digital Finance: DFIN <https://www.springer.com/finance/journal/42521>
Quantnet: www.quantlet.de/ <http://quantlet.de/>
Blockchain nights: blockchainnights.com <http://blockchainnights.com/>
Computer Museum: hu.berlin/cm <http://computermuseum.wiwi.hu-berlin.de/>

**Comment by lizzzi111** [comment]
ok, then. If you have any questions, you can contact Jane.

**Comment by amrimuhaimin** [comment]
Dear Liz and Prof Hardle,

I already change the script name to as same as QuantLet name.

**Pull request merged**
